
services:
  app:
    image: luiishs/deployjenkins:${TAG:-latest} # dinamica por si localmente quieres usar la imagen sin jenkins
    container_name: app
    ports:
      - "8080:80"
    environment:
      - ENV=production
      - DEBUG=False